### ISSUE TITLE
fails with trailing !

### ISSUE THREAD

**Issue by kevinranks** [kaoken/markdown-it-php#1]
First off, thank you @kaoken for putting this package together.

I noticed that the conversion currently fails if a line ends in `!` due to this line not checking if the index exists first: https://github.com/kaoken/markdown-it-php/blob/master/src/MarkdownIt/RulesInline/Image.php#L22

**Comment by yasuken2013** [comment]
Hi, @kevinranks.

Because I want to test it, please write the failed Markdown string and code.

**Example**
```
$md = new MarkdownIt('commonmark');
echo $md->render("Markdown string ...");
```

**Comment by kevinranks** [comment]
For me, your simple example failed:

Request: 
``` php
$md = new Kaoken\MarkdownIt\MarkdownIt();
$result = $md->render('# markdown-it rulezz!');
```
Result:
```
ErrorException in Kaoken\MarkdownIt\RulesInline\Image.php line 22:
Uninitialized string offset: 19
```

---

I also had an issue getting _linkify_ to work:

``` php
$md = new Kaoken\MarkdownIt\MarkdownIt(['linkify' => true]);
$result = $md->render('Will it automatically convert http://www.google.com to a link?');
```
Result:
```
ErrorException in Kaoken\LinkifyIt\LinkifyIt.php line 161:
preg_match_all(): Compilation failed: PCRE does not support \L, \l, \N{name}, \U, or \u at offset 15
```

**Comment by yasuken2013** [comment]
Thanks @kevinranks.

I confirmed two failures and fixed it immediately.
