### ISSUE TITLE
[FEATURE]: Additional Plugins

### ISSUE THREAD

**Issue by secondmanveran** [kaoken/markdown-it-php#10]
Hello.

I wanted to ask if there will be any further plugins added to the package?

Specifically:

1. [MarkdownItAttrs](https://github.com/arve0/markdown-it-attrs)
2. [anchor](https://github.com/valeriangalliat/markdown-it-anchor)
3. [Table of Contents](https://github.com/nagaozen/markdown-it-toc-done-right)

Thanks

**Comment by yasuken2013** [comment]
HI secondmanveran

Sorry for the late reply.

Unfortunately, I'm not thinking about adding plugins at the moment.

Thanks

**Comment by secondmanveran** [comment]
@kaoken 

No worries on the late reply, I appreciate it.

I guess I'll move along. 

Thanks
