### ISSUE TITLE
Rendering custom container

### ISSUE THREAD

**Issue by cmnstmntmn** [kaoken/markdown-it-php#3]
hei,

i tried rendering a custom container by using

```
::: custom_block
block content
::: custom_block
```

but it doesn't seem to be an easy way to render a custom layout.

are there any examples how this could be done?
since the documentation for custom containers is only for javascript, 
is not that easy to replicate it in php.

thank you.

**Comment by yasuken2013** [comment]
Sorry for the late reply.

Has the problem been solved already?
