### ISSUE TITLE
update to composer v2

### ISSUE THREAD

**Issue by dimanovoseltsev** [kaoken/markdown-it-php#6]
Class Kaoken\Test\MarkdownItTestgen\CTest located in ./vendor/kaoken/markdown-it-php/src/MarkdownIt/MarkdownItTestgen/CTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Kaoken\Test\MarkdownItTestgen\MarkdownItTestgen located in ./vendor/kaoken/markdown-it-php/src/MarkdownIt/MarkdownItTestgen/MarkdownItTestgen.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by yasuken2013** [comment]
Hi dimanovoseltsev

I fixed the pointed out part.

Thank you.
