### ISSUE TITLE
PHP 8 compatibility: match is a reserved keyword.

### ISSUE THREAD

**Issue by MadCat34** [kaoken/markdown-it-php#7]
Match is a reserved keyword in PHP 8.
Class Kaoken\LinkifyIt\Match must be renamed :-)

**Comment by MadCat34** [comment]
ping @kaoken :-)

**Comment by yasuken2013** [comment]
Hello MadCat34

Sorry for my late reply.

And thanks for pointing that out.

I will commit the fix in a few days.

Thanks

**Comment by MadCat34** [comment]
New PR #9 to close this issue
